name: facelock
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  awesome_notifications: ^0.10.1
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  card_swiper: ^3.0.1
  carousel_slider: ^5.1.1
  confetti: ^0.8.0
  dio: ^5.8.0+1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.10
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_map: ^8.1.1
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_staggered_animations: ^1.1.1
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  lottie: ^3.3.1
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
