name: facelock
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  camera: ^0.11.1
  card_swiper: ^3.0.1
  dio: ^5.8.0+1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  go_router: ^15.1.1
  google_sign_in: ^6.3.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  phosphor_flutter: ^2.1.0
  shimmer: ^3.0.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
